{% set name = "gazebo" %}
{% set version = "9.13.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:

  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version[0] }}_{{ version }}.tar.gz
    sha256: 3c724a79fa3cf3e2bf5026e81fd02664ecf0b62937944fda6dd675ed4626d9b1
    patches:
      - use-external-libs-config.patch
      - qwt-fix.patch
      - normalize-ogre-path.patch
      - fix_build.patch  # [unix]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
    - cmake
    - pkg-config

    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix]
    - {{ cdt('mesa-dri-drivers') }}  # [unix]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - libsdformat 6.*
    - libignition-transport4
    - qt 5.12.5
    - ogre 1.10.12
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp >=1.72
    - bzip2    # [osx]
    - zlib     # [osx]
    - libtar   # [unix]
    - libccd   # [unix]
  run:
    - libsdformat 6.*
    - libignition-transport4
    - qt 5.12.5
    - ogre 1.10.12
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp >=1.72

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Advanced robot simulator for research, design, and development.'

extra:
  recipe-maintainers:
    - seanyen
